name: gradle-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Clone Iris
      uses: actions/checkout@v2
      with:
        repository: 'The-HyperZone/Iris'
        ref: 'starline'
        path: 'Iris'
    - name: Publish Iris to Maven Local
      run: cd ./Iris && ./gradlew publishToMavenLocal && cd ..
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sodium-jars
        path: build/libs
